### ISSUE TITLE
Move footprints and deprecate this lib?

### ISSUE THREAD

**Issue by evanshultz** [KiCad/PFF_PSF_PSS_Leadforms.pretty#2]
These are for Allegro current sensors. Here is a datasheet that shows all three packages: http://radiodetali.com/media/catalog/product/a/c/acs758.pdf.

Allegro uses (in my experience) custom packages for this type of part:
- http://www.allegromicro.com/en/Products/Current-Sensor-ICs/Zero-To-Fifty-Amp-Integrated-Conductor-Sensor-ICs.aspx
- http://www.allegromicro.com/en/Products/Current-Sensor-ICs/Fifty-To-Two-Hundred-Amp-Integrated-Conductor-Sensor-ICs.aspx
- http://www.allegromicro.com/en/Products/Current-Sensor-ICs/SIP-Package-Zero-To-Thousand-Amp-Sensor-ICs.aspx

However, most of their packages are like a standard package such as SOIC, TSSOP, QFN, TO-220, etc. This library currently houses the TO-220-like Allegro footprints, and it seems silly to have an entire library that is just for these three parts (especially when the library names seems so poor). Could we put these footprints into another library, perhaps https://github.com/KiCad/TO_SOT_Packages_THT.pretty? I'll happily do the work if y'all agree.

There may be other Allegro-specific footprints in our library I haven't run across them.

EDIT: Somehow I accidentally pressed a but that submitted this comment before I finished it.

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr

**Comment by evanshultz** [comment]
@SchrodingersGat @jkriege2 @poeschlr @hackscribble

**Comment by SchrodingersGat** [comment]
@evanshultz I agree that the library name and subsequent footprint names are poor. However there is certainly value in having these footprints.

You say that they are "TO220-like" but the large current sense pins can be soldered down, and the shape of the component should be outlined on F.Fab and F.CrtYd.

What is a generic name for this "style" of package? The library should be renamed to something that is not specific to the Allegro name. 

Coming up with a better naming convention for this lib and the parts therein is the best solution IMO

**Comment by SchrodingersGat** [comment]
What about:  `Housings_LeadForm` ?

**Comment by evanshultz** [comment]
@SchrodingersGat 
Sorry if my accident with sending the initial message above caused confusion. I do want to keep these footprints, but I think they should live elsewhere rather than in a unique library just for the 3 of them.

Allegro calls this package CB and they have three different lead preps for it:
![image](https://user-images.githubusercontent.com/1936989/30621238-d80fbb2c-9d5e-11e7-9bce-22a9dae7f6d8.png)

Since they are TO220-like, I vote to move them to the TO_SOT_Housings_THT (the current lib name, anyway) repo and then deprecate this repo. That's where I'd look for these packages, anyway.

Similarly, they have a [SOIC-like package](http://www.allegromicro.com/en/Products/Current-Sensor-ICs/Fifty-To-Two-Hundred-Amp-Integrated-Conductor-Sensor-ICs/ACS780.aspx) that they call "PSOF" but I'd certainly check the Housings_SOIC repo if I wanted to find it. Even though Allegro uses their own names, I think we can group with like packages.

Any other suggestions, or is what I wrote above OK?

**Comment by SchrodingersGat** [comment]
TO-SOT THT works for me :)
